apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
      {{- include "library-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /opt/{{ .Values.deployment.path }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.deployment.image.image }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- with .Values.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          lifecycle:
            postStart:
              exec:
                {{- with .Values.deployment.command }}
                command:
                  {{- toYaml . | nindent 18 }}
                {{- end }}
          {{- with .Values.deployment.environment }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}